### ISSUE TITLE
第一次使用向导

### ISSUE THREAD

**Issue by steedos** [steedos/steedos-emailjs#60]
- 用户使用默认密码登录 Steedos
- 检测，如果用户没有mail_accounts记录，显示此向导
- 邮件用户名显示为Steedos账户名，不可修改。让用户输入邮件密码
- 点击验证，在客户端连接mail_domains中对应的邮件服务器验证
- 如果验证通过，自动创建 mail_accounts 记录，并自动更新当前用户的Steedos密码为邮件密码，同时把对应的邮件地址的verified设置为true
- 继续显示域账户设置界面
- 设置完成后关闭向导

**Comment by yinlianghui** [comment]
测试要点：
1. 进入除emailjs这个APP外任何一个APP内的url，都会在适用上述规则时弹出 账户设置窗口。
2. 点击完成按钮会关闭账户设置窗口，但是前提是当前账户至少有一条mail_accounts记录（只要一个工作区中有就算有，因为是作用是同步密码，且FSSH只有一个工作区）。
3. 手机版本经与庄总确定不用兼容，所以可以不测试，但是问题应该不大。
4. emailjs原先的密码加密解密这块被我改过了，改成调用全局加密解密函数，所以相关功能需要重新测试。
5. 之前Portal的单点登录密码没有加密，这次加密了，所以相关功能也要全部重新测试（只改了后台弹出IE单点登录需要调用的接口，应该没有其他地方需要修改，但是需要确定，特别是没有调用那个接口的地方）。
6. 要确认验证通过后密码是否能正常重新登录系统。
